--- @diagnostic disable-next-line: missing-fields
require("nvim-treesitter.configs").setup({
    ensure_installed = {
        "bash",
        "c",
        "css",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "html",
        "ini",
        "json",
        "lua",
        "markdown",
        "markdown_inline",
        "python",
        "query",
        "regex",
        "requirements",
        "sql",
        "ssh_config",
        "vim",
        "vimdoc",
    },
    indent = { enable = true },
    highlight = {
        disable = {
            "git_config",
            "git_rebase",
            "gitattributes",
            "gitcommit",
            "gitignore",
            "ini",
            "latex",
        },
        enable = true,
        additional_vim_regex_highlighting = false,
    },
    matchup = { enable = true },
})
vim.treesitter.language.register("bash", "zsh")
